services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: adminlocal
      MONGO_INITDB_ROOT_PASSWORD: gpocus8gwu7b9w2pl93lit2x77vo08
    volumes:
      - ./mongo-data:/data/db
    networks:
      - app-network

  database-service:
    build: ./database-service
    container_name: database-service
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    networks:
      - app-network

  backend-service:
    build: ./backend-service
    container_name: backend-service
    depends_on:
      - database-service
    environment:
      - DATABASE_SERVICE_URL=http:/database-service:8081
    ports:
      - "8082:8082"
    networks:
      - app-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - backend-service
    ports:
      - "8080:8080"
    networks:
      - app-network

  ui-service:

    build: ./ui-service
    container_name: ui-service
    depends_on:
      - api-gateway
    ports:
      - "3000:80"
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge